Códifo de transmissão da lista de vacinação
ImpulsoGov/bd pull request #12
Opened 2023-09-13 15:17 UTC by maaottoni

_**Criação do código de transmissão da lista nominal da vacinação**_

**Motivo do ajuste:**
Verificar funcionalidade do código que irá transmitir a primeira camada de dados para a construção da lista de vacinação.

**O que está sendo alterado:**
Inclusão do código de transmissão da lista de vacinação no repositório do transmissor.

_**Validações obrigatórias**_
- [] Código ajustado funcionando no back-up

2023-09-13 21:19 UTC, helenafig requested changes
Mai, no geral muito bom! ótimo trabalho! Fiz comentários onde precisaria de ajustes ou melhorias. Qualquer dúvida, me chama

2023-09-14 16:52 UTC, helenafig commented on Scripts/transmissor_impulso_esus/lista_nominal_vacinacao.sql
> +	    EXTRACT(YEAR FROM age(CURRENT_DATE::timestamp WITH time zone, tempocidadaopec.dt_registro::timestamp WITH time zone)) * 12 + EXTRACT(MONTH FROM age(CURRENT_DATE::timestamp WITH time zone, tempoc
cidadao_idade_atual

2023-09-14 16:53 UTC, helenafig commented on Scripts/transmissor_impulso_esus/lista_nominal_vacinacao.sql
> +	     EXTRACT(YEAR FROM age(dcp.data_inicio_quadrimestre::timestamp WITH time zone, dcp.dt_nascimento::timestamp WITH time zone)) * 12 + EXTRACT(MONTH FROM age(dcp.data_inicio_quadrimestre::timestamp
Mai, acho que poderiamos colocar idade_meses_inicio_do_quadri e idade_meses_fim_do_quadri, oq eu acha?
Tem outros campos de idade em outras listas e é sempre ano. Então acho importante essa diferenciação

2023-09-14 16:54 UTC, helenafig commented on Scripts/transmissor_impulso_esus/lista_nominal_vacinacao.sql
> +	    tfci.co_fat_cidadao_pec_responsvl as id_cidadao_pec_responsavel,
Como um cidadao poder ter mais de um cadastro é possivel que ele tenha mais de um co_fat_cidadao_pec_responsvl atrelado tbm. Podemos fazer um array_agg pra pegar o mais recente

2023-09-14 18:41 UTC, maaottoni reviewed
Correções pós comentários

2023-09-14 23:22 UTC, maaottoni reviewed
Aidciona código preliminar com as regras de negócio da lista  nominal de vacinação

2023-09-29 13:41 UTC, closed without merging