Cria campo de data de produção mais recente nos paineis das listas nominais
ImpulsoGov/bd pull request #18
Opened 2023-10-09 15:55 UTC by maaottoni

_**Alterações de código das listas nominais**_

**Motivo do ajuste:**
Melhoria dos paineis das listas nominais.

**O que está sendo alterado:**
Nos códigos atuais e futuros dos paineis das listas nominais é adicionada uma CTE que calcula por municipio e equipe quais as datas de produção mais recente e mais antigas, com base nas datas dos últimos atendimentos e últimos cadastros recebidos nas transmissões mais recentes de cada lista.

_**Validações obrigatórias**_

(Se modelagem no banco de dados)
- [x] Código ajustado funcionando no bd analítico

- [x] Check duplicados e variação de linhas 
- [] Check variações denominador e numerador do quadrimestre atual por município 

[Análises quantitativas nessa planilha](https://docs.google.com/spreadsheets/d/1SPUdqwJALbeaQgZTZaulcwtyzG5Yl41j3XNGnUZFuhI/edit#gid=0)

2023-10-09 17:38 UTC, helenafig requested changes
Muito bom Mai! só uma revisão a ser feita, depois pode implementar em prod

2023-10-09 17:38 UTC, helenafig commented on bd_analitico/esus-backups/impulso_previne_dados_nominais/views_materializadas/painel_enfermeiras_lista_nominal_gestantes.sql
> +        MAX(GREATEST(consulta_prenatal_ultima_data::date, acs_data_ultima_visita::date)) AS dt_registro_producao_mais_recente,
Mai, acho que tiraria essa acs_data_ultima_visita::date - para ficar igual a regra que teremos na api_fututo

2023-10-09 17:38 UTC, helenafig commented on bd_analitico/esus-backups/impulso_previne_dados_nominais/views_materializadas/painel_coordenadores_lista_nominal_gestantes.sql
> +        MAX(GREATEST(consulta_prenatal_ultima_data::date, acs_data_ultima_visita::date)) AS dt_registro_producao_mais_recente,
mesma coisa aqui

2023-10-09 17:57 UTC, maaottoni commented on bd_analitico/esus-backups/impulso_previne_dados_nominais/views_materializadas/painel_enfermeiras_lista_nominal_gestantes.sql
> +        MAX(GREATEST(consulta_prenatal_ultima_data::date, acs_data_ultima_visita::date)) AS dt_registro_producao_mais_recente,
Corrigido!

2023-10-09 17:57 UTC, maaottoni commented on bd_analitico/esus-backups/impulso_previne_dados_nominais/views_materializadas/painel_coordenadores_lista_nominal_gestantes.sql
> +        MAX(GREATEST(consulta_prenatal_ultima_data::date, acs_data_ultima_visita::date)) AS dt_registro_producao_mais_recente,
Corrigido!

2023-10-10 12:59 UTC, helenafig approved these changes

2023-10-10 12:59 UTC, merged