Regra de vinculação  - ajustes transmissões e listas unificadas
ImpulsoGov/bd pull request #32
Opened 2024-03-01 16:29 UTC by helenafig

_**Alterações de código das listas nominais**_

**Motivo do ajuste:**
A regra de vinculação foi remodelada tendo a adição de informações de equipe e profissional de atendimentos e procedimentos de cada cidadão.

**O que está sendo alterado:**
As transmissões das listas de hipertensão, diabetes e vacinação não possuíam parte das variáveis necessárias a modelagem da nova regra. Essas colunas foram adicionadas. Para tanto também foi feito:
- ajuste das DDLs das tabelas que recebem a transmissão
- ajuste das funções que unificam os schemas por município
- ajuste das views que consolidam as transmissões de todos os municípios

_**Validações obrigatórias**_

- [x] Código ajustado funcionando no back-up
testado no backup de Juquitiba set/23

[Códigos sql para validações quantitativas - Scripts/validacoes_listas_nominais](https://github.com/ImpulsoGov/bd/tree/b3e45be01efc4e82ce4985ed4df9af6d0f286a41/Scripts/validacoes_listas_nominais))
- [x] Check duplicados e variação de linhas 
- [x] Check variações denominador e numerador do quadrimestre atual no backup

[Análises quantitativas nessa planilha](https://docs.google.com/spreadsheets/d/1BgVW9reZdMe648aXy8NHmxsebiFqqkPq2QF05ruO97U/edit#gid=1165944503)

Próximos passos: 
- [] Comunicar ajustes importantes nos canais próprios de cada lista nominal
- [] Atualizar documentação de regras de negócio no [Notion](https://www.notion.so/impulsogov/Documenta-o-Listas-Nominais-8e919b380bc04783a02f2a74df9e81ce)

2024-03-04 14:48 UTC, maaottoni reviewed
[wip] Revisadas DDLs das tabelas e códigos de transmissão.

2024-03-04 20:37 UTC, maaottoni requested changes
Revisão finalizada. Em resumo:
- Códigos de transmissão funcionando corretamente
- Pequenos ajustes nas DDLs de diabeticos e hipertensos
- Ajustes no chamado das funções que criam as views de hipertensos, diabeticos e vacinacao (incluir os novos campos no FROM final)

2024-03-04 20:37 UTC, maaottoni commented on bd_analitico/esus-backups/impulso_previne_dados_nominais/views_materializadas/lista_nominal_diabeticos_unificada.sql
Ao criar a view, no FROM também precisa incluir os campos novos ao chamar a função consulta_tabelas_lista_nominal_diabeticos. Fica dessa forma: 
```
FROM impulso_previne_dados_nominais.consulta_tabelas_lista_nominal_diabeticos() 
   consulta_tabelas_lista_nominal_diabeticos(
   municipio_id_sus, 
   quadrimestre_atual, 
   realizou_solicitacao_hemoglobina_ultimos_6_meses,
   dt_solicitacao_hemoglobina_glicada_mais_recente, 
   realizou_consulta_ultimos_6_meses, 
   dt_consulta_mais_recente, 
   co_seq_fat_cidadao_pec, 
   cidadao_cpf, 
   cidadao_cns, 
   cidadao_nome, 
   cidadao_nome_social, 
   cidadao_sexo, 
   dt_nascimento, 
   estabelecimento_cnes_atendimento, 
   estabelecimento_cnes_cadastro, 
   estabelecimento_nome_atendimento, 
   estabelecimento_nome_cadastro, 
   equipe_ine_atendimento, 
   equipe_ine_cadastro, 
   equipe_ine_procedimento, 
   equipe_nome_atendimento, 
   equipe_nome_cadastro, 
   equipe_nome_procedimento,
   acs_nome_cadastro, 
   acs_nome_visita,
   profissional_nome_atendimento,
   profissional_nome_procedimento,
   possui_diabetes_autoreferida, 
   possui_diabetes_diagnosticada,
   data_ultimo_cadastro, 
   dt_ultima_consulta, 
   se_faleceu, 
   se_mudou, 
   criacao_data, 
   atualizacao_data)
```

2024-03-04 20:37 UTC, maaottoni commented on bd_analitico/esus-backups/impulso_previne_dados_nominais/views_materializadas/lista_nominal_hipertensos_unificada.sql
O mesmo que aconteceu na criação da view de diabeticos.
Ao final, tem que incluir no FROM ao chamar a função **consulta_tabelas_lista_nominal_hipertensos** os novos campos. Dessa forma:
```
FROM impulso_previne_dados_nominais.consulta_tabelas_lista_nominal_hipertensos()
   consulta_tabelas_lista_nominal_hipertensos(
   municipio_id_sus, 
   quadrimestre_atual, 
   realizou_afericao_ultimos_6_meses, 
   dt_afericao_pressao_mais_recente, 
   realizou_consulta_ultimos_6_meses, 
   dt_consulta_mais_recente, 
   co_seq_fat_cidadao_pec, 
   cidadao_cpf, 
   cidadao_cns, 
   cidadao_nome, 
   cidadao_nome_social, 
   cidadao_sexo, 
   dt_nascimento, 
   estabelecimento_cnes_atendimento, 
   estabelecimento_cnes_cadastro, 
   estabelecimento_nome_atendimento, 
   estabelecimento_nome_cadastro, 
   equipe_ine_atendimento, 
   equipe_ine_cadastro,
   equipe_ine_procedimento,
   equipe_nome_atendimento, 
   equipe_nome_cadastro,
   equipe_nome_procedimento,
   acs_nome_cadastro, 
   acs_nome_visita, 
   profissional_nome_atendimento,
   profissional_nome_procedimento,
   possui_hipertensao_autorreferida, 
   possui_hipertensao_diagnosticada, 
   data_ultimo_cadastro, 
   dt_ultima_consulta, 
   se_faleceu, 
   se_mudou, 
   criacao_data, 
   atualizacao_data)
```

2024-03-04 20:37 UTC, maaottoni commented on bd_analitico/esus-backups/impulso_previne_dados_nominais/views_materializadas/eventos_vacinacao.sql
No FROM, incluir no chamado da função o novo campo:
   FROM impulso_previne_dados_nominais.unir_tabelas_lista_nominal_vacinacao() unir_tabelas_lista_nominal_vacinacao(municipio_id_sus, chave_cidadao, cidadao_nome, cidadao_cpf, cidadao_cns, cidadao_sexo, dt_nascimento, cidadao_nome_responsavel, cidadao_cns_responsavel, cidadao_cpf_responsavel, cidadao_idade_meses_atual, cidadao_idade_meses_inicio_quadri, cidadao_idade_meses_fim_quadri, se_faleceu, co_seq_fat_vacinacao, co_seq_fat_vacinacao_vacina, tipo_ficha, codigo_vacina, nome_vacina, dose_vacina, data_registro_vacina, estabelecimento_cnes_aplicacao_vacina, estabelecimento_nome_aplicacao_vacina, equipe_ine_aplicacao_vacina, equipe_nome_aplicacao_vacina, profissional_nome_aplicacao_vacina, data_ultimo_cadastro_individual, estabelecimento_cnes_cadastro, estabelecimento_nome_cadastro, equipe_ine_cadastro, equipe_nome_cadastro, acs_nome_cadastro, estabelecimento_cnes_atendimento, estabelecimento_nome_atendimento, equipe_ine_atendimento, equipe_nome_atendimento, **profissional_nome_atendimento**, data_ultimo_atendimento_individual, data_ultima_vista_domiciliar, acs_nome_visita, criacao_data)

2024-03-05 13:53 UTC, helenafig commented on transmissor_impulso_esus/ddls_tabelas_transmitidas/diabeticos.sql
>  	dt_nascimento date NULL,
Feito!

2024-03-05 13:53 UTC, helenafig commented on transmissor_impulso_esus/ddls_tabelas_transmitidas/diabeticos.sql
> +	equipe_nome_procedimento
Feito!

2024-03-05 13:54 UTC, helenafig commented on transmissor_impulso_esus/ddls_tabelas_transmitidas/hipertensos.sql
> +	equipe_nome_procedimento
Feito

2024-03-05 13:56 UTC, helenafig commented on bd_analitico/esus-backups/impulso_previne_dados_nominais/views_materializadas/lista_nominal_diabeticos_unificada.sql
Feito!

2024-03-05 13:57 UTC, helenafig commented on bd_analitico/esus-backups/impulso_previne_dados_nominais/views_materializadas/lista_nominal_hipertensos_unificada.sql
Feito!

2024-03-05 13:57 UTC, helenafig commented on bd_analitico/esus-backups/impulso_previne_dados_nominais/views_materializadas/eventos_vacinacao.sql
Feito!

2024-03-05 14:20 UTC, merged